name: Dummy deploy
description: 'This is not real deploy'

inputs:
  app_name:
    description: 'Application name'
    required: true
  environment:
    description: 'Target environment for deployment'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build the application
      id: build
      shell: bash
      run: echo "Building application ${{ inputs.app_name }}"

    - name: Deploy application
      id: deploy
      shell: bash
      run: |
        echo "Deploying application to ${{ inputs.environment }}"
        echo "::set-output name=deployStatus::success"        

    - name: Notify success
      id: notify_success
      if: steps.deploy.outputs.deployStatus == 'success'
      shell: bash
      run: echo "Notify the new deployment"
    
    - name: Notify error
      id: notify_error
      if: steps.deploy.outputs.deployStatus != 'success'
      shell: bash
      run: echo "Notify the team about the error"